[features]
seeds = false
skip-lint = false

[programs.localnet]
orchestrator = "5xoTHKz9USUXd1WZu5Dkg7pFXsKXytmGJ1R2yLWJjzqR"
vault = "8zj9vrBBuQuJx5YnrNvPWwchz8vA6xdLdwVz7NKbnZYL"
exchange = "7F2HX2UdZCFj5DJTgFXgD5qMv8HTCrXDoUgr2bXzqShL"
staking = "9HJNMnsfb82WhdXACjGU9T2L7ZdbHZ1FKbwqHPHDuwVs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kernlog/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
